server:
  port: 8001
spring:
  application:
    name: mongo-admin
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mongo?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      filters: stat,wall,log4j,config           #配置监控
      max-active: 100   #最大连接数
      initial-size: 1   #初始化大小
      max-wait: 60000   #获取连接等待操时时间
      min-idle: 1       #最小连接数
      time-between-eviction-runs-millis: 60000  #间隔多久才进行一次检验，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000    #一个连接在池中最小生存的时间，单位是毫秒
      validation-query: select 'x'
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name} # 注册到consul的服务名称
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
pagehelper:                #参考文章 https://www.2cto.com/database/201703/613116.html
  helper-dialect: mysql
  reasonable: true        #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  support-methods-arguments: true
  params: count=countSql