server:
   port: 8000
spring:
  application:
    name: mongo-monitor
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  boot:
    admin:
      discovery:
        ignored-services: "consul"